services:
  roboflow-inference:
    image: roboflow/roboflow-inference-server-gpu:latest
    volumes:
      - /d/YOLO_cache:/cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  telegram-bot:
    image: system205/grocery-bot:latest
    environment:
      web-client.base-url: http://roboflow-inference:9001/
    env_file:
      - ./tokens.txt
