bot:
  token: ${BOT_TOKEN}
  owner-id: ${OWNER_ID}

infer:
  request:
    model-id: grocery-products-detection/4
    model-type: object-detection
    api-key: ${API_KEY}
    confidence: 0.715
    iou-threshold: 0.5